# Generated by Django 2.2.7 on 2020-01-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('Student_name', models.CharField(default='', editable=False, max_length=50)),
                ('Class', models.CharField(max_length=4)),
                ('Section', models.CharField(max_length=50)),
                ('SCHOOL_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('class_teacher', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
