# Generated by Django 2.2.7 on 2020-01-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(max_length=4),
        ),
    ]
