# Generated by Django 2.2.7 on 2020-01-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_db', '0002_auto_20200110_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(max_length=50),
        ),
    ]
