# Generated by Django 2.2.7 on 2019-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher_db',
            new_name='school_db',
        ),
    ]
