# Generated by Django 2.2.7 on 2019-12-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0003_auto_20191219_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='practicle',
            field=models.IntegerField(default=''),
        ),
    ]
