# Generated by Django 2.2.7 on 2019-12-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0005_auto_20191220_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='practicle',
            field=models.IntegerField(),
        ),
    ]
