# Generated by Django 2.2.7 on 2019-12-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_db', '0007_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='practicle',
            new_name='Prac',
        ),
    ]
